/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_my_myapplication_CameraActivity */

#ifndef _Included_com_my_myapplication_CameraActivity
#define _Included_com_my_myapplication_CameraActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_my_myapplication_CameraActivity
 * Method:    judge
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_my_myapplication_CameraActivity_judge
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     com_my_myapplication_CameraActivity
 * Method:    initDetect
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_my_myapplication_CameraActivity_initDetect
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
